# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'InstagramViewer' do

pod ‘Parse’, ‘~> 1.7.1’
pod ‘ParseUI’, ‘~> 1.1.3’
pod 'ParseCrashReporting'

end
target 'InstagramViewerTests' do

end

target 'InstagramViewerUITests' do

end

