# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

def testing_pods
    pod 'Quick', '~> 0.9.0'
    pod 'Nimble', '3.0.0'
end

target 'UICollectionInUITableViewCell' do

end

target 'UICollectionInUITableViewCellTests' do
    testing_pods
end

target 'UICollectionInUITableViewCellUITests' do
    testing_pods
end
