# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'HearthstoneCards' do
pod 'Mantle'
pod 'Realm'
pod 'AFNetworking'
pod 'SDWebImage', '~>3.7'
end

target 'HearthstoneCardsTests' do

end

target 'HearthstoneCardsUITests' do

end

