# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'DribbbleViewer' do
pod 'Mantle'
pod 'Realm'
pod 'AFNetworking'
pod 'FLAnimatedImage'
end

target 'DribbbleViewerTests' do

end

target 'DribbbleViewerUITests' do

end

