# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'DatebuttonsScrolls' do

end

target 'DatebuttonsScrollsTests' do
  pod 'Nimble'
	pod 'Quick'
end

target 'DatebuttonsScrollsUITests' do
  pod 'KIF', :configurations => ['Debug']
    pod 'Nimble'
  pod 'Quick'
end
