# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'DatebuttonsScrolls' do
  pod 'Quick'
  pod 'Nimble'
end

target 'DatebuttonsScrollsTests' do
  pod 'Quick'
  pod 'Nimble'
end

target 'DatebuttonsScrollsUITests' do
  pod 'Quick'
  pod 'Nimble'
end
