# Uncomment this line to define a global platform for your project
platform :ios, '7.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'CSBilling' do
pod 'Google/SignIn'
end

target 'CSBillingTests' do

end

target 'CSBillingUITests' do

end
