# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'Bike 2 Work' do
pod 'Alamofire'
pod 'AlamofireObjectMapper'
end

target 'Bike 2 WorkTests' do
pod 'Quick'
pod 'Nimble'
end

target 'Bike 2 WorkUITests' do

end

